#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname $0)/.."

echo "webpack"
webpack

echo "docker login"
docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io

echo "docker build -t ${REPO}:${TAG}"
docker build -t $REPO:$TAG .

echo "docker push ${REPO}:${TAG}"
docker push $REPO:$TAG

if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  echo "docker tag ${REPO}:${TAG} ${REPO}:latest"
  docker tag $REPO:$TAG $REPO:latest

  echo "docker push ${REPO}:latest"
  docker push $REPO:latest
fi
